---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-16.04
  run_list:
  - recipe[apt]
- name: ubuntu-18.04
  run_list:
  - recipe[apt]
- name: debian-9
  run_list:
  - recipe[apt]
- name: debian-10
  run_list:
  - recipe[apt]

suites:
- name: dvwa-mysql
  run_list:
  - recipe[dvwa]
