---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
- name: dvwa-mysql
  run_list:
  - recipe[dvwa]
  attributes:
    dvwa:
      db:
        use_pgsql: false
- name: dvwa-postgresql
  run_list:
  - recipe[postgresql::apt_pgdg_postgresql]
  - recipe[postgresql::client]
  - recipe[dvwa::pg_omnibus]
  - recipe[dvwa::gem_pg]
  - recipe[postgresql::server]
  - recipe[dvwa]
  attributes:
    postgresql:
      password:
        postgres: postgres
    dvwa:
      db:
        use_pgsql: true
